"""empty message

Revision ID: 196ab027ad34
Revises: 79b1063bcc1a
Create Date: 2024-08-01 06:05:18.829956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196ab027ad34'
down_revision = '79b1063bcc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['current_owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_owner_id')

    # ### end Alembic commands ###
