"""empty message

Revision ID: 443f9c1fab9e
Revises: 13fb68d60713
Create Date: 2024-08-02 07:37:06.315289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443f9c1fab9e'
down_revision = '13fb68d60713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('type_l', sa.String(length=50), nullable=False),
    sa.Column('type_m', sa.String(length=50), nullable=False),
    sa.Column('air_temperature', sa.Float(), nullable=False),
    sa.Column('process_temperature', sa.Float(), nullable=False),
    sa.Column('rorational_speed', sa.Float(), nullable=False),
    sa.Column('torque', sa.Float(), nullable=False),
    sa.Column('tool_wear', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_history')
    op.drop_table('meter_readings')
    # ### end Alembic commands ###
