"""empty message

Revision ID: 4afc9495fea3
Revises: 443f9c1fab9e
Create Date: 2024-08-02 08:41:07.212903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afc9495fea3'
down_revision = '443f9c1fab9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prediction', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.drop_column('prediction')

    # ### end Alembic commands ###
